services:
  - type: web
    name: financas-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: MONGODB_URI
        value: ${MONGODB_URI}
